main: me.scyphers.fruitservers.skyhole.SkyHole
name: SkyHole
version: 1.4.1
api-version: 1.17
author: Scyphers
depend:
  - WorldGuard
commands:
  skyhole:
    description: "Create skyholes and reload the plugin"